# Shell variables
# Generated by 'wal'
wallpaper='/home/daniil/.config/wpg/wallpapers/AmqDCxX.jpg'

# Special
background='#303036'
foreground='#c4c4b5'
cursor='#c4c4b5'

# Colors
color0='#303036'
color1='#9b6546'
color2='#6f8583'
color3='#a19373'
color4='#687183'
color5='#796a70'
color6='#47676e'
color7='#c4c4b5'
color8='#585858'
color9='#9b6546'
color10='#6f8583'
color11='#a19373'
color12='#687183'
color13='#796a70'
color14='#47676e'
color15='#c4c4b5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
