# Shell variables
# Generated by 'wal'
wallpaper='/home/daniil/Wallpapers/5143iq08pr831.jpg'

# Special
background='#06181F'
foreground='#e4c7d9'
cursor='#e4c7d9'

# Colors
color0='#06181F'
color1='#698C9C'
color2='#9688A6'
color3='#B18BAD'
color4='#CE94B9'
color5='#D8A0BA'
color6='#B1A6C8'
color7='#e4c7d9'
color8='#9f8b97'
color9='#698C9C'
color10='#9688A6'
color11='#B18BAD'
color12='#CE94B9'
color13='#D8A0BA'
color14='#B1A6C8'
color15='#e4c7d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
