--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="~/Wallpapers/wp2448301-hiroshi-nagai-wallpapers.jpg"

-- Special
background="#1c1c1c"
foreground="#efefef"
cursor="#efefef"

-- Colors
color0="#1c1c1c"
color1="#af99ed"
color2="#8e94f2"
color3="#9fa0ff"
color4="#bbadff"
color5="#d7b8fe"
color6="#7d7abc"
color7="#c1c1c1"
color8="#3b4252"
color9="#7c6c8f"
color10="#807bc0"
color11="#6869b2"
color12="#726d9b"
color13="#ceadf3"
color14="#5a5787"
color15="#efefef"
