--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniil/.config/wpg/wallpapers/AmqDCxX.jpg"

-- Special
background="#303036"
foreground="#c4c4b5"
cursor="#c4c4b5"

-- Colors
color0="#303036"
color1="#9b6546"
color2="#6f8583"
color3="#a19373"
color4="#687183"
color5="#796a70"
color6="#47676e"
color7="#c4c4b5"
color8="#585858"
color9="#9b6546"
color10="#6f8583"
color11="#a19373"
color12="#687183"
color13="#796a70"
color14="#47676e"
color15="#c4c4b5"
