#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
blueman-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 20


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled manage=on
bspc rule -a zathura state=tiled manage=on
bspc rule -a Inkscape desktop='^2'
bspc rule -a inkscape desktop='^2'
bspc rule -a firefox desktop='^3'
feh --randomize --bg-fill ~/Wallpapers/
#xdo above -t $(xdo id -n root) $(xdo id -n lemonbar)
xrdb -merge .Xresources
inkscape-figures watch
wal -R
$HOME/.config/polybar/launch.sh
picom &
